### PR TITLE
Support aishrc (scripts)

### LINKED ISSUE #6: Create aishrc (config)
Configuration:
- AI model

### PR DESCRIPTION
**Pull request by CraigNewlands**
image

### CODE REVIEW

**Comment by CraigNewlands** [comment]
Not sure if we want to include an example .aishrc in the code?

**Comment by siliconlad** [comment]
> Not sure if we want to include an example .aishrc in the code?

We probably want to explain the setup instructions in the README, because the user will have to create a new `.aishrc` file in their home directory and add their openai api key to it.

That should be enough.

Edit: I can do that in #71

**Comment by siliconlad** [comment]
Also, I think if we can pull out the code, we can easily execute other script files which would be insanely cool :)

**Review by siliconlad — COMMENTED** [review]
Also, I think if we can pull out the code, we can easily execute other script files which would be insanely cool :)

Something like aish -f script.ai

Edit: not sure if .ai or .aish is a better extension.

**Comment by siliconlad** [comment]
@CraigNewlands can you take a look.

I made it so that it:
1. Looks for the `~/.aishrc` file and execute that
2. If run with `aish file` then executes that file
3. If run with `aish` then interactive mode is enabled

**Comment by CraigNewlands** [comment]
Looks good to me

**Pull request merged**
